services:
  couchbase:
    image: couchbase/server:latest
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      - CLUSTER_HOSTNAME=couchbase
      - CLUSTER_INIT_USERNAME=admin
      - CLUSTER_INIT_PASSWORD=password
      - SERVICES=data,index,query
      - NODE_INIT_NODE_TYPE=kv
      - NODE_INIT_RAM_SIZE_MB=512
      - NODE_INIT_INDEX_MEM_QUOTA_MB=256
    volumes:
      - couchdb:/opt/couchdb/data
    networks:
      - couchbase

  content-service:
    image: bugbusters/content-service
    container_name: content-service
    ports:
      - "8084:8084"
    networks:
      - couchbase
      - kafka-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - COUCHBASE_BUCKET_NAME=content-metadata
      - COUCHBASE_BUCKET_USERNAME=admin
      - COUCHBASE_BUCKET_PASSWORD=password
      - COUCHBASE_CLUSTER_CONNECTION_STRING=couchbase
      - COUCHBASE_CLUSTER_USERNAME=admin
      - COUCHBASE_CLUSTER_PASSWORD=password
    command: >
      bash -c "cd home"
      bash -c "mkdir -p /content"
    depends_on:
      - couchbase
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

networks:
  couchbase:
    driver: bridge
  kafka-network:
    driver: bridge

volumes:
  couchdb:
