version: '3'
volumes:
  db:

services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
