version: "3.9"

volumes:
  user_management_postgres:

services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_management
    volumes:
      - user_management_postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  
  # Make sure that you close tab that were connected to pgAdmin before start the container.
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: on-failure