version: "3.9"

volumes:
  user_management_postgres:
  redis_data:

services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_management
    volumes:
      - user_management_postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
      image: 'redis:latest'
      ports:
        - '6379:6379'
      volumes:
        - redis_data:/data

  spring-boot-app:
      image: user_management
      ports:
        - '8080:8080'
      depends_on:
          - pgdatabase
          - redis

  # Make sure that you close tab that were connected to pgAdmin before start the container.
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - pgdatabase
