version: '3'

services:
    haproxy:
        image: haproxytech/haproxy-ubuntu:latest
        container_name: haproxy
        networks:
            - mynetwork
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - "80:80"
            - "8404:8404"
            - "1936:1936"
            - "443:443"
            - "8080:8080"
            - "9999:9999"
        restart: unless-stopped

networks:
    mynetwork:
