name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Docker username
        run: |
              echo ${{ secrets.DOCKER_USERNAME }}
              echo ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bugbusters
          password: mcwU&EzgtvG27Y


      - name: Build with Maven and push Docker image
        run: |
          mvn clean compile package
          mvn -P build-docker-image jib:build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
